language: node_js

node_js:
  - 5.11

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm run-script test

notifications:
  email: false
